name: Build for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 cmake make

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ ..

    - name: Build with Make
      run: |
        cd build
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build-output
        path: build/*.exe
