name: Build for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MinGW and Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqt5websockets5-dev

    - name: Set environment for MinGW
      run: |
        export CC=x86_64-w64-mingw32-gcc
        export CXX=x86_64-w64-mingw32-g++
        export PATH=/usr/bin:$PATH

    - name: Configure with qmake
      run: qmake -spec win32-g++

    - name: Build with make
      run: mingw32-make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-build-output
        path: build/*.exe
