name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Update Git submodules
      run: git submodule update --init --recursive

    - name: Install Qt dependencies
      run: sudo apt-get install -y qt5-qmake qtbase5-dev libqt5websockets5-dev

    - name: Configure with qmake
      run: qmake

    - name: Build with make
      run: make

    - name: Run tests
      run: make check

    - name: Run distcheck
      run: make distcheck
